image: ruby:2.2

before_script:
  - gem install awesome_bot

build:
  script:
  - awesome_bot README.md --allow-dupe --white-list awesome-django,django-pagination,djangobeer,django-dynamic-preferences.,djangovillage
